const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_CLLLECTIONS_FAILURE: 'FETCH_cOLLECTIONS_FAILURE'
};

export default ShopActionTypes;