version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm run install-packages
      - run: CI=true npm run build
  test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "testing"
      - run: npm run install-packages
      - run: npm test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
